theme: jekyll-theme-minimal
title: Welcome to prototypingplanner.com
logo: prototypingplanner.github.io/logo.png
description: Here you can find supporting material for our research publications about the use of prototyping in product development. Take a look around.

// [Camilla Arndt Hansen](https://www.researchgate.net/profile/Camilla_Hansen25), PhD student at the Technical University of Denmark

show_downloads: false
google_analytics:
